### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by guinanlin** [ONE-F-M/One-FM#2649]
my envoirement as follwoing:
ERPNext: v14.36.0 (version-14)
Frappe Framework: v14.46.0 (version-14)
Frappe HR: v15.0.0-dev (develop)
===============================================
try to install on docker,happen to following error:

frappe@bdfcb63885d2:~/frappe-bench$ bench build --app one_fm
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 61, in build
    frappe.init("")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 252, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1553, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1393, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1342, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/frappe/frappe-bench/apps/one_fm/one_fm/__init__.py", line 11, in <module>
    from one_fm.api.doc_methods.payroll_entry import (
  File "/home/frappe/frappe-bench/apps/one_fm/one_fm/api/doc_methods/payroll_entry.py", line 16, in <module>
    from hrms.payroll.doctype.payroll_entry.payroll_entry import (
ImportError: cannot import name 'get_filter_condition' from 'hrms.payroll.doctype.payroll_entry.payroll_entry' (/home/frappe/frappe-bench/apps/hrms/hrms/payroll/doctype/payroll_entry/payroll_entry.py)

**Comment by mymi14s** [comment]
Install

hrms
payments

**Comment by mymi14s** [comment]
@guinanlin you Don seem to read your logs. It clearly state that some apps are missing. Read it and fix accordingly

**Comment by guinanlin** [comment]
I have install the app:
Installed Apps
ERPNext: v15.0.0-dev (version-15-beta)
Frappe Framework: v15.0.0-dev (version-15-beta
Frappe HR: v15.0.0-dev (develop)
Payments: v0.0.1 (develop)

but wihle get-app https://github.com/ONE-F-M/One-FM.git get the following error:
`
frappe@12e77fccaaf2:~/frappe-bench/apps$ bench get-app https://github.com/ONE-F-M/One-FM.git
Getting One-FM
$ git clone https://github.com/ONE-F-M/One-FM.git  --depth 1 --origin upstream
Cloning into 'One-FM'...
remote: Enumerating objects: 5182, done.
remote: Counting objects: 100% (5182/5182), done.
remote: Compressing objects: 100% (4299/4299), done.
remote: Total 5182 (delta 1252), reused 3998 (delta 826), pack-reused 0
Receiving objects: 100% (5182/5182), 102.53 MiB | 7.92 MiB/s, done.
Resolving deltas: 100% (1252/1252), done.
Updating files: 100% (5126/5126), done.
Ignoring dependencies of https://github.com/ONE-F-M/One-FM.git. To install dependencies use --resolve-deps
Installing one_fm
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/one_fm 
$ bench build --app one_fm
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 75, in get_app_commands
    app_command_module = importlib.import_module(f"{app}.commands")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/frappe/frappe-bench/apps/one_fm/one_fm/__init__.py", line 11, in <module>
    from one_fm.api.doc_methods.payroll_entry import (
  File "/home/frappe/frappe-bench/apps/one_fm/one_fm/api/doc_methods/payroll_entry.py", line 16, in <module>
    from hrms.payroll.doctype.payroll_entry.payroll_entry import (
ImportError: cannot import name 'get_filter_condition' from 'hrms.payroll.doctype.payroll_entry.payroll_entry' (/home/frappe/frappe-bench/apps/hrms/hrms/payroll/doctype/payroll_entry/payroll_entry.py)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 44, in app_group
    ctx.obj = {"sites": get_sites(site), "force": force, "verbose": verbose, "profile": profile}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 56, in get_sites
    elif default_site := frappe.get_conf().default_site:
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 372, in get_conf
    with init_site(site):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 382, in __enter__
    init(self.site)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 246, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1602, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1461, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1426, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1456, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1397, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/frappe/frappe-bench/apps/one_fm/one_fm/__init__.py", line 11, in <module>
    from one_fm.api.doc_methods.payroll_entry import (
  File "/home/frappe/frappe-bench/apps/one_fm/one_fm/api/doc_methods/payroll_entry.py", line 16, in <module>
    from hrms.payroll.doctype.payroll_entry.payroll_entry import (
ImportError: cannot import name 'get_filter_condition' from 'hrms.payroll.doctype.payroll_entry.payroll_entry' (/home/frappe/frappe-bench/apps/hrms/hrms/payroll/doctype/payroll_entry/payroll_entry.py)
ERROR: bench build --app one_fm
subprocess.CalledProcessError: Command 'bench build --app one_fm' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 242, in install
    install_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 586, in install_app
    build_assets(bench_path=bench_path, app=app)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/bench.py", line 351, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: bench build --app one_fm

INFO: A newer version of bench is available: 5.17.0 → 5.17.1`

**Comment by mymi14s** [comment]
If you read the information you'll know we are running on version 14
--
Sent from Mail.ru app for Android Tuesday, 29 August 2023, 11:48pm +01:00 from hawk  ***@***.*** :

**Comment by guinanlin** [comment]
thanks for your kind reply. 

I rebuilt a 14 version environment:
ERPNext: v14.36.0 (version-14)
Frappe Framework: v14.46.0 (version-14)
Frappe HR: v14.10.3 (version-14)
Payments: v0.0.1 (version-14)

The first step executed without any problems.
**bench get-app https://github.com/ONE-F-M/One-FM.git**

However, in the second step,
**bench install-app one_fm**

I encountered the following error:

frappe@01771e501689:~/frappe-bench$ bench --site site1.local install-app one_fm
App frappe already installed
App erpnext already installed

Installing one_fm...
Checking if Landmark facial recogintion exists... ./site1.local/private/files/
Facial recognition found!.
Updating DocTypes for one_fm        : [===============                         ] 38%An error occurred while installing one_fm: (1054, "Unknown column 'company_name_arabic' in 'field list'")
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 297, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1277, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 912, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 407, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 492, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1342, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/one_fm/one_fm/grd/doctype/fingerprint_appointment/fingerprint_appointment.py", line 13, in <module>
    from one_fm.grd.doctype.medical_insurance import medical_insurance
  File "apps/one_fm/one_fm/grd/doctype/medical_insurance/medical_insurance.py", line 14, in <module>
    from one_fm.grd.doctype.moi_residency_jawazat import moi_residency_jawazat
  File "apps/one_fm/one_fm/grd/doctype/moi_residency_jawazat/moi_residency_jawazat.py", line 15, in <module>
    class MOIResidencyJawazat(Document):
  File "apps/one_fm/one_fm/grd/doctype/moi_residency_jawazat/moi_residency_jawazat.py", line 16, in MOIResidencyJawazat
    company = frappe.db.get_value("Company", frappe.defaults.get_global_default('company'),
  File "apps/frappe/frappe/database/database.py", line 509, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 606, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 835, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'company_name_arabic' in 'field list'")

**Comment by Z4nzu** [comment]
> thanks for your kind reply.
> 
> I rebuilt a 14 version environment: ERPNext: v14.36.0 (version-14) Frappe Framework: v14.46.0 (version-14) Frappe HR: v14.10.3 (version-14) Payments: v0.0.1 (version-14)
> 
> The first step executed without any problems. **bench get-app https://github.com/ONE-F-M/One-FM.git**
> 
> However, in the second step, **bench install-app one_fm**
> 
> I encountered the following error:
> 
> frappe@01771e501689:~/frappe-bench$ bench --site site1.local install-app one_fm App frappe already installed App erpnext already installed
> 
> Installing one_fm... Checking if Landmark facial recogintion exists... ./site1.local/private/files/ Facial recognition found!. Updating DocTypes for one_fm : [=============== ] 38%An error occurred while installing one_fm: (1054, "Unknown column 'company_name_arabic' in 'field list'") Traceback (most recent call last): File "apps/frappe/frappe/commands/site.py", line 415, in install_app _install_app(app, verbose=context.verbose, force=force) File "apps/frappe/frappe/installer.py", line 297, in install_app sync_for(name, force=force, reset_permissions=True) File "apps/frappe/frappe/model/sync.py", line 109, in sync_for import_file_by_path( File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path import_doc( File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc doc.insert() File "apps/frappe/frappe/model/document.py", line 285, in insert self.run_post_save_methods() File "apps/frappe/frappe/model/document.py", line 1088, in run_post_save_methods self.run_method("on_update") File "apps/frappe/frappe/model/document.py", line 915, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "apps/frappe/frappe/model/document.py", line 1277, in composer return composed(self, method, *args, **kwargs) File "apps/frappe/frappe/model/document.py", line 1259, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "apps/frappe/frappe/model/document.py", line 912, in fn return method_object(*args, **kwargs) File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 407, in on_update self.run_module_method("on_doctype_update") File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 492, in run_module_method module = load_doctype_module(self.name, self.module) File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module doctype_python_modules[key] = frappe.get_module(module_name) File "apps/frappe/frappe/**init**.py", line 1342, in get_module return importlib.import_module(modulename) File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "apps/one_fm/one_fm/grd/doctype/fingerprint_appointment/fingerprint_appointment.py", line 13, in from one_fm.grd.doctype.medical_insurance import medical_insurance File "apps/one_fm/one_fm/grd/doctype/medical_insurance/medical_insurance.py", line 14, in from one_fm.grd.doctype.moi_residency_jawazat import moi_residency_jawazat File "apps/one_fm/one_fm/grd/doctype/moi_residency_jawazat/moi_residency_jawazat.py", line 15, in class MOIResidencyJawazat(Document): File "apps/one_fm/one_fm/grd/doctype/moi_residency_jawazat/moi_residency_jawazat.py", line 16, in MOIResidencyJawazat company = frappe.db.get_value("Company", frappe.defaults.get_global_default('company'), File "apps/frappe/frappe/database/database.py", line 509, in get_value result = self.get_values( File "apps/frappe/frappe/database/database.py", line 606, in get_values out = self._get_values_from_table( File "apps/frappe/frappe/database/database.py", line 835, in _get_values_from_table return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck) File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query result = frappe.db.sql(query, params, *args, **kwargs) # nosemgrep File "apps/frappe/frappe/database/database.py", line 220, in sql self._cursor.execute(query, values) File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute result = self._query(query) File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query conn.query(q) File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query self._affected_rows = self._read_query_result(unbuffered=unbuffered) File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result result.read() File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read first_packet = self.connection._read_packet() File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet packet.raise_for_error() File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error err.raise_mysql_exception(self._data) File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception raise errorclass(errno, errval) pymysql.err.OperationalError: (1054, "Unknown column 'company_name_arabic' in 'field list'")

#3479 Fixed in this PR

**Comment by mymi14s** [comment]
Hi, we are on version 15

Emmanuel Anthony
________________________________
